/control/execute main/macros/run_tierB_paper_default_1M.mac
/analysis/setFileName outputs\tierB_paper_default_50k_thick725\B02ntuples_tierB_paper_default_50k_thick725.root
/analysis/ntuple/setFileName 0 outputs\tierB_paper_default_50k_thick725\B02ntuples_tierB_paper_default_50k_thick725.root
/analysis/ntuple/setFileName 1 outputs\tierB_paper_default_50k_thick725\B02ntuples_tierB_paper_default_50k_thick725.root
/runAction/useTimeSeed false
/runAction/useFixedSeeds true
/runAction/seed1 12345
/runAction/seed2 67890
/runAction/macroPath C:\Users\cmore\geant4\g4work\SimCCD_Log_Complete\outputs\tierB_paper_default_50k_thick725\run_driver_50k.mac
/runAction/provenanceTag tierB_paper_default_50k_thick725
/run/printProgress 10000
/run/initialize
/run/beamOn 50000
